name: Google Santa Screenshot

on:
  schedule:
    - cron: "0 */3 * * *"  # 3時間ごとに実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  take_screenshots:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v4

      - name: Pythonのセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 必要なパッケージをインストール
        run: |
          python -m pip install --upgrade pip
          pip install selenium pillow pillow-avif-plugin

      - name: スクリーンショットを撮影
        run: |
          python screenshot.py

      - name: 変更をコミット
        run: |
          git pull
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add screenshots/*
          git commit -m "Add new screenshots"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
