name: Santa Screenshot

on:
  schedule:
    - cron: '5 7 24 12 *'
    - cron: '50 8 24 12 *' # 12/24 17:50
    - cron: '50 12 24 12 *' # 12/24 20:50
    - cron: '50 14 24 12 *' # 12/24 23:50
    - cron: '50 17 24 12 *'  # 12/25 2:50
    - cron: '50 20 24 12 *'  # 12/25 5:50
    - cron: '50 23 24 12 *'  # 12/25 8:50
    - cron: '50 2 25 12 *' # 12/25 11:50
    - cron: '50 5 25 12 *' # 12/25 14:50

jobs:
  screenshot_job:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install selenium

      - name: Set up FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Execute Python script
        run: |
          python main.py

      - name: Create Release
        run: |
          gh release create videos 
          gh release upload videos output_*.av1
