name: Screenshot to Video

on:
  workflow_dispatch:  # 手動実行も可能

jobs:
  capture_and_video:
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: 必要なツールをインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk-extra
          pip3 install selenium
          wget https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
          tar xf ffmpeg-*

      - name: スクリーンショットを撮影
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python screenshot.py

      - name: 動画を生成
        run: |
          ./ffmpeg-master-latest-linux64-gpl/bin/ffmpeg -framerate 60 -i screenshots/santa_%04d.png -c:v libsvtav1 -preset 6 -crf 35 output.mp4

      - name: リリースを作成して動画をアップロード
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "santa-$(date +'%Y%m%d%H%M%S')" output.mp4 \
            --title "Santa Tracker Video" \
            --notes "This video was generated from screenshots taken every 10 seconds."
